---
- name: Activate epel repository on RedHat systems
  ansible.builtin.package:
    name: epel-release
  when: ansible_os_family == 'RedHat'

- name: Install certbot package
  ansible.builtin.package:
    name: certbot

# This task should remove custom service definitions created by previous version of this role.
# Certbot package come with a renew service definitions itself, why not using it?
# It will renew all registred certificates by default and does not limit us on some domains.
# You can remove this task on later versions.
- name: Remove custom certbot services definition
  ansible.builtin.file:
    path: '/etc/systemd/system/{{ item }}'
    state: absent
  loop:
    - certbot-renew.service
    - certbot-renew.timer
  notify: Enable certbot

- name: Start certbot service
  ansible.builtin.service:
    name: certbot-renew.timer
    state: started
    enabled: true

- name: Generate initial certificate
  ansible.builtin.shell:
    cmd: >
      certbot -n
      -a webroot
      --webroot-path /var/lib/nginx/
      --agree-tos
      -m {{ opencast_letsencrypt_email }}
      certonly
      --domains {{ inventory_hostname }}
    creates: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem

- name: Symlink certificates
  ansible.builtin.file:
    src: /etc/letsencrypt/live/{{ item.src }}
    dest: /etc/nginx/ssl/{{ item.dest }}
    state: link
    force: true
  loop:
    - src: '{{ inventory_hostname }}/fullchain.pem'
      dest: '{{ inventory_hostname }}.crt'
    - src: '{{ inventory_hostname }}/privkey.pem'
      dest: '{{ inventory_hostname }}.key'
  notify: reload nginx
