---
- name: Activate epel repository on RedHat systems
  ansible.builtin.package:
    name: epel-release
  when: ansible_os_family == 'RedHat'

- name: Install certbot package
  ansible.builtin.package:
    name: certbot

- name: Install certbot services
  ansible.builtin.template:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'
  loop:
    - certbot-renew.service
    - certbot-renew.timer
  notify: Restart certbot

- name: Start certbot service
  ansible.builtin.service:
    name: certbot-renew.timer
    state: started
    enabled: true

- name: Generate initial certificate
  ansible.builtin.shell:
    cmd: >
      certbot -n
      -a webroot
      --webroot-path /var/lib/nginx/
      --agree-tos
      -m {{ opencast_letsencrypt_email }}
      certonly
      --domains {{ inventory_hostname }}
      --deploy-hook "{{ opencast_certbot_deploy_hook | default(None) }}"
    creates: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem

- name: Symlink certificates
  ansible.builtin.file:
    src: /etc/letsencrypt/live/{{ item.src }}
    dest: /etc/nginx/ssl/{{ item.dest }}
    state: link
    force: true
  loop:
    - src: '{{ inventory_hostname }}/fullchain.pem'
      dest: '{{ inventory_hostname }}.crt'
    - src: '{{ inventory_hostname }}/privkey.pem'
      dest: '{{ inventory_hostname }}.key'
  notify: reload nginx
